import type { CatalogCard, CollectionItem, Conversation, Post, User, VcaNotification } from "./types";

const ART = {
  ember: "https://r2-pub.rork.com/projects/6cu1lfh2z1a14gllh5wnf/assets/759bb147-848c-4b81-94c2-8bcaaa8e6eba.png",
  tide: "https://r2-pub.rork.com/projects/6cu1lfh2z1a14gllh5wnf/assets/69b0841e-2cc3-4126-a254-35d14897af83.png",
  verdant: "https://r2-pub.rork.com/projects/6cu1lfh2z1a14gllh5wnf/assets/92a75ecc-24bd-40f9-a34b-9938c891d74c.png",
  volt: "https://r2-pub.rork.com/projects/6cu1lfh2z1a14gllh5wnf/assets/d408858d-d994-4523-a75a-518a5c994379.png",
  psy: "https://r2-pub.rork.com/projects/6cu1lfh2z1a14gllh5wnf/assets/9834be7f-3b5a-43fd-a2ac-1beb55eca62d.png",
  abyss: "https://r2-pub.rork.com/projects/6cu1lfh2z1a14gllh5wnf/assets/09ec5d79-d9c9-49c3-9a53-f6fde3d57aa1.png",
};

function history(base: number, metric: number, months: string[]) {
  const series = [0.78, 0.84, 0.8, 0.88, 0.92, 0.9, 0.97, 1.0].map((f) => Math.round(base * metric * f));
  return months.map((month, i) => ({ month, value: series[i] }));
}

const MONTHS = ["Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"];

export const CATALOG: CatalogCard[] = [
  {
    id: "charizard-base",
    name: "Charizard",
    pokemon: "Charizard",
    set: "Base Set",
    number: "4/102",
    rarity: "Holo Rare",
    year: 1999,
    language: "English",
    variant: "Unlimited · Holo",
    type: "Fire",
    artKey: "ember",
    artUrl: ART.ember,
    tcgCardId: "pokemon-base-set-charizard-holo-rare",
    prices: { raw: 425, g10: 1150, g9: 680, g8: 470 },
    priceDate: "Sep 18, 2026",
    priceSource: "VCA Market Index · aggregated sales",
    history: history(1150, 1, MONTHS),
    historyMetric: "VCA 10",
  },
  {
    id: "blastoise-base",
    name: "Blastoise",
    pokemon: "Blastoise",
    set: "Base Set",
    number: "2/102",
    rarity: "Holo Rare",
    year: 1999,
    language: "English",
    variant: "Unlimited · Holo",
    type: "Water",
    artKey: "tide",
    artUrl: ART.tide,
    tcgCardId: "pokemon-base-set-blastoise-holo-rare",
    prices: { raw: 210, g10: 540, g9: 320, g8: 240 },
    priceDate: "Sep 18, 2026",
    priceSource: "VCA Market Index · aggregated sales",
    history: history(540, 1, MONTHS),
    historyMetric: "VCA 10",
  },
  {
    id: "venusaur-base",
    name: "Venusaur",
    pokemon: "Venusaur",
    set: "Base Set",
    number: "15/102",
    rarity: "Holo Rare",
    year: 1999,
    language: "English",
    variant: "Unlimited · Holo",
    type: "Grass",
    artKey: "verdant",
    artUrl: ART.verdant,
    tcgCardId: "pokemon-base-set-venusaur-holo-rare",
    prices: { raw: 180, g10: 470, g9: 285, g8: 205 },
    priceDate: "Sep 18, 2026",
    priceSource: "VCA Market Index · aggregated sales",
    history: history(470, 1, MONTHS),
    historyMetric: "VCA 10",
  },
  {
    id: "pikachu-base",
    name: "Pikachu",
    pokemon: "Pikachu",
    set: "Base Set",
    number: "58/102",
    rarity: "Common",
    year: 1999,
    language: "English",
    variant: "Unlimited",
    type: "Electric",
    artKey: "volt",
    artUrl: ART.volt,
    tcgCardId: "pokemon-base-set-pikachu-common",
    prices: { raw: 95, g10: 260, g9: 150, g8: 110 },
    priceDate: "Sep 18, 2026",
    priceSource: "VCA Market Index · aggregated sales",
    history: history(260, 1, MONTHS),
    historyMetric: "VCA 10",
  },
  {
    id: "mewtwo-base",
    name: "Mewtwo",
    pokemon: "Mewtwo",
    set: "Base Set",
    number: "10/102",
    rarity: "Holo Rare",
    year: 1999,
    language: "English",
    variant: "Unlimited · Holo",
    type: "Psychic",
    artKey: "psy",
    artUrl: ART.psy,
    tcgCardId: "pokemon-base-set-mewtwo-holo-rare",
    prices: { raw: 160, g10: 420, g9: 250, g8: 180 },
    priceDate: "Sep 18, 2026",
    priceSource: "VCA Market Index · aggregated sales",
    history: history(420, 1, MONTHS),
    historyMetric: "VCA 10",
  },
  {
    id: "gyarados-base",
    name: "Gyarados",
    pokemon: "Gyarados",
    set: "Base Set",
    number: "6/102",
    rarity: "Holo Rare",
    year: 1999,
    language: "English",
    variant: "Unlimited · Holo",
    type: "Water",
    artKey: "abyss",
    artUrl: ART.abyss,
    tcgCardId: "pokemon-base-set-gyarados-holo-rare",
    prices: { raw: 240, g10: 610, g9: 360, g8: 260 },
    priceDate: "Sep 18, 2026",
    priceSource: "VCA Market Index · aggregated sales",
    history: history(610, 1, MONTHS),
    historyMetric: "VCA 10",
  },
];

export const cardById = (id: string): CatalogCard | undefined => CATALOG.find((c) => c.id === id);

export const USERS: User[] = [
  {
    id: "u-todd",
    username: "toddslabs",
    displayName: "Todd",
    bio: "Base Set chaser since '99. VCA believer. If it's not slabbed, it's not finished. 🔥",
    location: "Austin, TX",
    favoritePokemon: "Charizard",
    favoriteSet: "Base Set",
    level: 12,
    joined: "2024",
    online: true,
    badges: ["Founding Collector", "Grading Pro", "Holo Hunter", "Base Set Master"],
    stats: { cards: 247, graded: 42, value: 18240, favorites: 18 },
    avatarHue: 190,
    isSelf: true,
  },
  {
    id: "u-bella",
    username: "basesetbella",
    displayName: "Bella",
    bio: "WOTC era only. Shadowless enthusiast. Currently hunting a PSA-equivalent VCA 10 Venusaur.",
    location: "Toronto, CA",
    favoritePokemon: "Venusaur",
    favoriteSet: "Base Set",
    level: 9,
    joined: "2024",
    online: true,
    badges: ["Holo Hunter", "Early Adopter"],
    stats: { cards: 183, graded: 27, value: 9450, favorites: 12 },
    avatarHue: 130,
  },
  {
    id: "u-max",
    username: "shinyhuntermax",
    displayName: "Max",
    bio: "Modern sets + Japanese exclusives. My scanner runs hotter than my Charizard.",
    location: "Berlin, DE",
    favoritePokemon: "Pikachu",
    favoriteSet: "151",
    level: 7,
    joined: "2025",
    online: false,
    badges: ["Scanner Ace", "Community Pick"],
    stats: { cards: 412, graded: 15, value: 6210, favorites: 22 },
    avatarHue: 55,
  },
  {
    id: "u-guru",
    username: "gradingguru",
    displayName: "Kenji",
    bio: "Grading analyst. I look at print lines the way other people look at sunsets.",
    location: "Osaka, JP",
    favoritePokemon: "Mewtwo",
    favoriteSet: "Base Set",
    level: 15,
    joined: "2024",
    online: true,
    badges: ["Grading Pro", "Founding Collector", "Authenticity Lab"],
    stats: { cards: 96, graded: 88, value: 24800, favorites: 9 },
    avatarHue: 275,
  },
];

export const userById = (id: string): User => USERS.find((u) => u.id === id) ?? USERS[0];

export const CURRENT_USER_ID = "u-todd";

export const COLLECTION: CollectionItem[] = [
  { id: "i1", cardId: "charizard-base", ownerId: "u-todd", addedAt: "2026-09-14", grade: "VCA 10", serial: "VCA-D-26-0104", slab: "digital", favorite: true, wishlist: false, quantity: 1 },
  { id: "i2", cardId: "charizard-base", ownerId: "u-todd", addedAt: "2026-08-30", grade: null, serial: null, slab: "none", favorite: false, wishlist: false, quantity: 1 },
  { id: "i3", cardId: "blastoise-base", ownerId: "u-todd", addedAt: "2026-09-02", grade: "VCA 9", serial: "VCA-D-26-0091", slab: "digital", favorite: false, wishlist: false, quantity: 1 },
  { id: "i4", cardId: "venusaur-base", ownerId: "u-todd", addedAt: "2026-07-19", grade: "VCA 8", serial: "VCA-D-26-0066", slab: "digital", favorite: false, wishlist: false, quantity: 1 },
  { id: "i5", cardId: "gyarados-base", ownerId: "u-todd", addedAt: "2026-09-10", grade: null, serial: null, slab: "none", favorite: true, wishlist: false, quantity: 1 },
  { id: "i6", cardId: "pikachu-base", ownerId: "u-todd", addedAt: "2026-06-05", grade: "VCA 10", serial: "VCA-D-26-0031", slab: "physical", favorite: true, wishlist: false, quantity: 1 },
  { id: "i7", cardId: "mewtwo-base", ownerId: "u-todd", addedAt: "2026-05-21", grade: null, serial: null, slab: "none", favorite: false, wishlist: true, quantity: 1 },
  { id: "i8", cardId: "charizard-base", ownerId: "u-bella", addedAt: "2026-09-08", grade: "VCA 9", serial: "VCA-D-26-0117", slab: "digital", favorite: true, wishlist: false, quantity: 1 },
  { id: "i9", cardId: "venusaur-base", ownerId: "u-bella", addedAt: "2026-08-22", grade: "VCA 10", serial: "VCA-D-26-0110", slab: "digital", favorite: false, wishlist: false, quantity: 1 },
  { id: "i10", cardId: "gyarados-base", ownerId: "u-guru", addedAt: "2026-09-12", grade: "VCA 10", serial: "VCA-D-26-0120", slab: "physical", favorite: true, wishlist: false, quantity: 1 },
  { id: "i11", cardId: "mewtwo-base", ownerId: "u-guru", addedAt: "2026-09-01", grade: "VCA 10", serial: "VCA-D-26-0118", slab: "physical", favorite: false, wishlist: false, quantity: 1 },
  { id: "i12", cardId: "pikachu-base", ownerId: "u-max", addedAt: "2026-09-16", grade: null, serial: null, slab: "none", favorite: false, wishlist: false, quantity: 1 },
];

export const POSTS: Post[] = [
  {
    id: "p1",
    userId: "u-todd",
    time: "2h",
    text: "Just added this Charizard to my collection 🔥 Scanner pulled it at $425 raw. Now the real question… slab it or send it in?",
    images: [],
    card: { cardId: "charizard-base", grade: null, serial: null, caption: "NEW ADDITION" },
    likes: 84,
    likedByMe: false,
    comments: [
      { id: "c1", userId: "u-bella", text: "That centering 👀 send it to VCA", time: "1h" },
      { id: "c2", userId: "u-max", text: "GEM MINT potential for sure", time: "48m" },
    ],
    shares: 6,
    saved: false,
    kind: "post",
  },
  {
    id: "p2",
    userId: "u-guru",
    time: "5h",
    text: "VCA 10 — GEM MINT 💎 The print lines on this Gyarados are flawless. Physical NFC slab just activated.",
    images: [],
    card: { cardId: "gyarados-base", grade: "VCA 10", serial: "VCA-D-26-0120", caption: "NEW GRADE · VCA 10" },
    likes: 212,
    likedByMe: true,
    comments: [{ id: "c3", userId: "u-todd", text: "Absolute stunner. Congrats Kenji!", time: "4h" }],
    shares: 18,
    saved: true,
    kind: "grade",
  },
  {
    id: "p3",
    userId: "u-max",
    time: "8h",
    text: "Just scanned this card. Current market value: $95 raw, $260 at VCA 10. The scanner even caught the off-center back. Technology is wild.",
    images: [],
    card: { cardId: "pikachu-base", grade: null, serial: null, caption: "SCANNER RESULT" },
    likes: 41,
    likedByMe: false,
    comments: [],
    shares: 2,
    saved: false,
    kind: "scan",
  },
  {
    id: "p4",
    userId: "u-bella",
    time: "12h",
    text: "Finally finished the Base Set holo starter trio 🌿 VCA 10 on the Venusaur sealed the deal.",
    images: [],
    card: { cardId: "venusaur-base", grade: "VCA 10", serial: "VCA-D-26-0110", caption: "TRIO COMPLETE" },
    likes: 156,
    likedByMe: false,
    comments: [{ id: "c4", userId: "u-guru", text: "The Venusaur is criminally underrated.", time: "9h" }],
    shares: 11,
    saved: false,
    kind: "slab",
  },
];

export const CONVERSATIONS: Conversation[] = [
  {
    id: "conv1",
    userId: "u-bella",
    unread: 2,
    messages: [
      { id: "m1", fromMe: false, text: "Todd! Is that Base Charizard you scanned still raw?", time: "09:41" },
      { id: "m2", fromMe: true, text: "Yeah it is. Thinking about sending it to VCA for grading.", time: "09:45" },
      { id: "m3", fromMe: false, text: "Do it. I'll trade you my 1st Ed Arcanine if the grade comes back VCA 10 👀", time: "09:46" },
      { id: "m4", fromMe: false, text: "Also — do you still have that Venusaur slab?", time: "09:46" },
    ],
  },
  {
    id: "conv2",
    userId: "u-guru",
    unread: 0,
    messages: [
      { id: "m5", fromMe: true, text: "Kenji, what did your Gyarados grade at?", time: "Yesterday" },
      { id: "m6", fromMe: false, text: "VCA 10 Gem Mint. The NFC slab is gorgeous in person.", time: "Yesterday" },
      { id: "m7", fromMe: true, text: "Insane. Mine's going in next batch.", time: "Yesterday" },
    ],
  },
  {
    id: "conv3",
    userId: "u-max",
    unread: 1,
    messages: [
      { id: "m8", fromMe: false, text: "Check out this scan result — the price engine caught a 14% jump on Pikachu this month", time: "08:12" },
    ],
  },
];

export const NOTIFICATIONS: VcaNotification[] = [
  { id: "n1", kind: "grade", text: "Your Pikachu Base Set returned from VCA grading: VCA 10 Gem Mint 💎", time: "1h", read: false, cardId: "pikachu-base" },
  { id: "n2", kind: "like", userId: "u-bella", text: "Bella liked your post about the Base Charizard", time: "2h", read: false },
  { id: "n3", kind: "connection", userId: "u-guru", text: "Kenji sent you a connection request", time: "5h", read: false },
  { id: "n4", kind: "price", text: "Price alert: Charizard Base Set (VCA 10) up 6.4% this week", time: "9h", read: true, cardId: "charizard-base" },
  { id: "n5", kind: "wishlist", text: "Wishlist match: Mewtwo Base Set appeared in Max's collection", time: "1d", read: true, cardId: "mewtwo-base" },
];

export const TRENDING = [
  { cardId: "charizard-base", delta: "+6.4%", rank: 1 },
  { cardId: "gyarados-base", delta: "+4.1%", rank: 2 },
  { cardId: "venusaur-base", delta: "+2.8%", rank: 3 },
  { cardId: "blastoise-base", delta: "+1.9%", rank: 4 },
  { cardId: "mewtwo-base", delta: "-0.6%", rank: 5 },
  { cardId: "pikachu-base", delta: "+0.8%", rank: 6 },
];

export const ACTIVITY = [
  { userId: "u-guru", text: "activated NFC slab VCA-26-A-0001 · Gyarados VCA 10", time: "18m" },
  { userId: "u-bella", text: "completed the Base Set starter trio", time: "12h" },
  { userId: "u-max", text: "scanned 12 cards today", time: "14h" },
  { userId: "u-guru", text: "submitted 3 cards for VCA professional grading", time: "1d" },
  { userId: "u-bella", text: "created digital slab VCA-D-26-0110 · Venusaur VCA 10", time: "1d" },
];

export const SETS = ["Base Set", "Jungle", "Fossil", "Team Rocket", "Base Set 2", "151"];
